name: Gene Kogan
markdown: kramdown
collections:
  chapters:
    output: true
    permalink: /ml4a/:path/
  chapters_cn:
    output: true
    permalink: /ml4a/cn/:path/
  chapters_ko:
    output: true
    permalink: /ml4a/ko/:path/
  chapters_es:
    output: true
    permalink: /ml4a/es/:path/
  guides:
    output: true
    permalink: /guides/:path/